// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CustomersManagementProjectML.Model
{
    public class ModelInput
    {
        [ColumnName("ItemId"), LoadColumn(0)]
        public float ItemId { get; set; }


        [ColumnName("Rating"), LoadColumn(1)]
        public float Rating { get; set; }


        [ColumnName("Categorie"), LoadColumn(2)]
        public float Categorie { get; set; }


        [ColumnName("Description"), LoadColumn(3)]
        public string Description { get; set; }


        [ColumnName("Quantity"), LoadColumn(4)]
        public float Quantity { get; set; }


        [ColumnName("Store_name"), LoadColumn(5)]
        public string Store_name { get; set; }


        [ColumnName("Store_location"), LoadColumn(6)]
        public string Store_location { get; set; }


        [ColumnName("SerialKey"), LoadColumn(7)]
        public string SerialKey { get; set; }


        [ColumnName("ItemName"), LoadColumn(8)]
        public string ItemName { get; set; }


        [ColumnName("Price"), LoadColumn(9)]
        public float Price { get; set; }


        [ColumnName("Date_of_purchase"), LoadColumn(10)]
        public string Date_of_purchase { get; set; }


    }
}
